server {
    listen 80;
    server_name _;
    charset utf-8;
    client_max_body_size 20m;

    root /usr/share/nginx/html;
    index index.html;

  location / {
    try_files $uri $uri/ /index.html;
  }

  location /api/auth/ {
    proxy_pass http://auth-service:8081/api/auth/;
  }

  location /api/problem/ {
    proxy_pass http://problem-service:8082/api/problem/;
  }

  location /api/submission/ {
    proxy_pass http://problem-service:8082/api/submission/;
  }

  location /api/judge/ {
    proxy_pass http://judge-service:8083/api/judge/;
  }

  location /api/ai/ {
    proxy_pass http://ai-service:8085/api/ai/;
  }

  location /api/statistics/ {
    proxy_pass http://statistics-service:8086/api/statistics/;
  }

  location /api/teacher/ {
    proxy_pass http://teacher-service:8087/api/teacher/;
  }
}
