global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: spring-services
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - "auth-service:8081"
          - "problem-service:8082"
          - "judge-service:8083"
          - "sandbox-service:8084"
          - "ai-service:8085"
          - "statistics-service:8086"
          - "teacher-service:8087"
